WIP feat: circle progress bar web component
bdryanovski/clarity pull request #6
Opened 2019-08-29 13:02 UTC by bdryanovski

## PR Checklist

Please check if your PR fulfills the following requirements:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

New component 

* [ ] Bugfix
* [x] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [x] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #2245

## What is the new behavior?

## Does this PR introduce a breaking change?

* [ ] Yes
* [X] No

## Other information

fork of this [commit](https://github.com/mathisscott/clarity/commit/cc8832d48b80c6ea9ad60014e7facf5b104889fd#diff-6aa29cf5b8face85c6fe29446c8c1739) from @mathisscott

2019-08-29 14:54 UTC, mathisscott requested changes
Thanks for jumping in on this, @bdryanovski 

I think the big takeaway here is that this component still needs a lot of work. And a good chunk of that work needs the web component library to be a little further along than it is right now.

I'd recommend working on this when you can but focusing your efforts on bugs and features for clarity angular in the near term. Once we have custom properties finished and clearer contribution guidelines, I think you can pick this up and finish it out fairly quickly.

2019-08-29 14:54 UTC, mathisscott commented on src/clr-angular/progress/circle-progress/circle-progress.ts
> +  set clrMedium(value: boolean | string) {
Making a bunch of booleans for sizing is not necessary.

2019-08-29 14:54 UTC, mathisscott commented on src/clr-angular/progress/circle-progress/circle-progress.ts
> +  get setAriaLive() {
aria needs to go on the web component

2019-08-29 14:54 UTC, mathisscott commented on src/clr-base/components/clr-wc-circular-progress/clr-wc-circular-progress.ts
> +function polarToCartesian(centerX: number, centerY: number, radius: number, angleInDegrees: number) {
this file needs many more unit tests

2019-08-29 14:54 UTC, mathisscott commented on src/clr-base/components/clr-wc-circular-progress/clr-wc-circular-progress.ts
> +const BACKGROUND_COLOR: string = 'hsl(201, 10%, 90%)';
these should be handled by CSS variables

2019-08-29 14:54 UTC, mathisscott commented on src/clr-base/components/clr-wc-circular-progress/clr-wc-circular-progress.ts
> +    font-family: inherit;
this should be pulled out into a utility SCSS file and shared across all web components.

this also needs to have the SASS-to-JS set up for it.

2019-08-29 14:54 UTC, mathisscott commented on src/dev/src/app/custom-props/custom-props.demo.ts
> +    if (this.pctComplete + 5 > 100) {
this needs its own demo and own demo page.

Cory and I think the web components need their own dev-app as well. You should get with him on next steps for that.

2019-08-29 14:54 UTC, mathisscott commented on src/dev/src/app/web-component/circle-progress/wc-circle-progress.demo.html
> +                    <clr-wc-circular-progress [size]="24" [progress]="pctComplete"></clr-wc-circular-progress>
if we know the size in this placement is 24, we shouldn't require users to set it

2019-08-29 14:54 UTC, mathisscott commented on src/dev/src/app/web-component/circle-progress/wc-circle-progress.demo.html
> +                            <clr-wc-circular-progress [size]="18" [progress]="pctComplete"></clr-wc-circular-progress>
same here

2019-08-29 14:54 UTC, mathisscott commented on src/dev/src/app/custom-props/custom-props.demo.html
> +  <span style="width: 36px; height: 36px; display: inline-block; margin-right: 12px">
we also need indeterminate circular progress. Eventually, it should lead to the deprecation and removal of the spinner.

And the positioning of these circular progress bars needs to be added to the container components in Colin's file.

And we need to deprecate the linear progress bars in cards and sidenavs.

2019-08-29 16:44 UTC, bdryanovski reviewed
Thanks for the quick review,

Pretty much everything here is WIP. And more or less experimenting with the component.

Also, notice a few things that are not ready yet but will be nice to have: 

 * We need to have a separate documentation page for Web components - how to embed them and what type of API-s they provide.
* On the topic for unit test - we could go again with Jasmine I think with a little change we could go and use almost the same setup, there few recommended web component testing frameworks out there - did not spend a lot of time researching them, but we definitely need something.
* We need to move some of the styles into web component to limit the duplication of the styles.

2019-08-29 16:44 UTC, bdryanovski commented on src/clr-angular/progress/circle-progress/circle-progress.ts
> +  set clrMedium(value: boolean | string) {
This is part of the idea to have the same API as clrSpinner and clrProgressBar. 

we could try something like that:
```html
<clr-circle-progress size="medium"></clr-circle-progress>
```

But we gonna have inconsistent API between spinner and progress-bar. 

Other option will be to get its size from outside container 
```html
<div class="clr-circle-progress-md-size">
  <clr-circle-progress></clr-circle-progress>
</div>
```

2019-08-29 16:44 UTC, bdryanovski commented on src/clr-base/components/clr-wc-circular-progress/clr-wc-circular-progress.ts
> +function polarToCartesian(centerX: number, centerY: number, radius: number, angleInDegrees: number) {
we need a lot of tests ;)

2019-08-29 16:44 UTC, bdryanovski commented on src/clr-base/components/clr-wc-circular-progress/clr-wc-circular-progress.ts
> +    font-family: inherit;
I think that there is a plugin for that...

2019-08-29 16:44 UTC, bdryanovski commented on src/dev/src/app/web-component/circle-progress/wc-circle-progress.demo.html
> +                    <clr-wc-circular-progress [size]="24" [progress]="pctComplete"></clr-wc-circular-progress>
From the design and screenshot I saw that there could be more than one element in the form of Icon or Progress into the header of the card so - here there must be some content that may be will order them and limit there size.

Right now is just there to remind me to fix it

2019-08-29 16:44 UTC, bdryanovski commented on src/dev/src/app/web-component/circle-progress/wc-circle-progress.demo.scss
> +.cpbMedium {
.cpbMedium, cpbSmall and cpbMini are no longer valid styles

2019-08-29 17:23 UTC, mathisscott requested changes

2019-08-29 17:23 UTC, mathisscott commented on src/clr-angular/progress/circle-progress/_circle-progress.clarity.scss
> +    border: 1px solidd red;
typo. also not using global border width. i'm assuming red is for testing?

2019-08-29 17:25 UTC, mathisscott commented on src/clr-angular/progress/circle-progress/circle-progress.ts
> +  set clrMedium(value: boolean | string) {
these types of questions about the API are things that Cory and I need some time to review. we don't have an answer for it at the moment and this effort would be blocked until we do.

2019-08-29 17:26 UTC, mathisscott commented on src/clr-base/components/clr-wc-circular-progress/clr-wc-circular-progress.ts
> +    font-family: inherit;
we already have a solution worked out. we haven't had the opportunity to apply it yet.

i'm still working on custom properties (which is a blocker for all web components).

it will be some time before you can dive into this.

2019-08-29 17:29 UTC, mathisscott commented
All of the bullet points you have listed are things I've pointed out in the review.

The project isn't ready for contributions right now. It's cool that you are experimenting. And when we've ironed out these details, you should be able to refactor your code, create a react wrapper, and contribute it fairly quickly.

Right now, i'm working on getting things set up. Cory will be too, soon. Give us a few weeks and then circle back.

2019-08-29 17:31 UTC, coryrylan commented
Thanks for being interested in helping with Clarity Base. We currently have a lot of the build infrastructure and architecture work in progress or missing. We are also as tracking issues and priorities specific to Base in a private repo because we are not ready to announce anything public yet.

Many of these tasks are being worked on or will be worked on by the devs that were assigned to work on clarity base. Until those things are worked out, this component will be blocked. The project in its current state cannot support web components nor be tested and deployed correctly.

It will take some time before we are ready for component contributions outside of the devs that were assigned to work on Clarity Base full time. Once that work is completed, then this component will be ready to be worked on. 👍

2019-08-30 11:33 UTC, bdryanovski commented on src/clr-angular/progress/circle-progress/_circle-progress.clarity.scss
> +    border: 1px solidd red;
yep it is ;)

2019-08-31 19:14 UTC, pumano commented on src/dev/src/app/custom-props/custom-props.demo.html
> +  <span style="width: 36px; height: 36px; display: inline-block; margin-right: 12px">
@mathisscott why deprecate linear progress bars in cards? I use it. Very useful ;)

2020-02-27 11:37 UTC, closed without merging

2020-02-27 11:45 UTC, pumano commented
It should not been implemented?

2020-02-27 14:05 UTC, mathisscott commented
@pumano 
This PR was close but we have a lot of code guidelines that were not yet in place when the PR was opened. @bdryanovski is going to be helping us with the web component initiative over the next few months (starting when he's got the 👍 from the angular side of the equation).

We have a medium-sized starter task to get him familiar with the web component library then he and I will be revisiting this component. We'll be pairing up on it. So I'd expect another PR in a May-June timeframe at the latest.

2020-02-27 16:42 UTC, pumano commented
@mathisscott sorry for offtopic, but want to say about having web components lib is very useful, because it's possible to reuse with any framework. Very good initiative.

2020-02-27 16:47 UTC, bdryanovski commented
The branch is not deleted but moved so I won't delete it by mistake. 

There is a lot of initial work for web-components that we need to do before continuing with new component, but we are getting there.